# Generated by Django 4.1.5 on 2023-01-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event/images'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_video',
            field=models.FileField(blank=True, null=True, upload_to='event/videos'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='stages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/speakers_images'),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/sponsors_images'),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentcoordinators',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/student_coordinators_images'),
        ),
        migrations.AlterField(
            model_name='studentcoordinators',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentcouncilmembers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/student_council_images'),
        ),
        migrations.AlterField(
            model_name='studentcouncilmembers',
            name='position',
            field=models.CharField(blank=True, choices=[('P', 'President'), ('R', 'Vice President'), ('S', 'Secretary'), ('T', 'Treasurer'), ('JS', 'Joint Secretary'), ('JT', 'Joint Treasurer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachercoordinators',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/teacher_coordinator_images'),
        ),
        migrations.AlterField(
            model_name='teachercoordinators',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='techfest',
            name='college_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='techfest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='techfest',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techfest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='techfest',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techfest',
            name='fest_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='techfest',
            name='fest_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='techfest',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techfest',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techfest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='techfest',
            name='short_description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='techfest',
            name='society_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='techfest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='techfest',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techfest',
            name='university_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='event/videos'),
        ),
    ]
